apiVersion: v1
kind: Service
metadata:
  name: {{ include "shoppingassistant.fullname" . }}
  labels:
    app: {{ .Values.app }}
    env: {{ .Values.env }}
    region: {{ .Values.region }}
{{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app }}
    env: {{ .Values.env }}
    region: {{ .Values.region }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort.name }}
      protocol: TCP
      name: "http"
    - port: {{ .Values.service.portHttps }}
      targetPort: {{ .Values.service.targetPort.name }}
      protocol: TCP
      name: "https"