{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "shoppingassistant.serviceAccountName" . }}
  labels:
{{ include "shoppingassistant.labels" . | indent 4 }}
{{- end -}}